version: "3.8"
services:
  webapache:
    container_name: servapache
    build: 
      context: ./../
      dockerfile: ./prueba1/dockerfile
      #dockerfile: ./prueba1/dockerfile_httpd
    ports:
      - "8080:80"
    volumes:
      - ../web/var/www/html